---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jzldtsmy/public_html/way2writersnew
    - /bin/cp -r . $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev
    - /usr/local/bin/php artisan optimize
    - /usr/local/bin/php artisan migrate --force
